name: Apptainer CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.1.2

    - name: Clean disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo apt-get clean
    
    - name: Build the Apptainer image
      run: |
        cd build
        apptainer build dronalize.sif apptainer.def

    - name: Download Data
      run: |
        wget -O synthD.zip "https://liuonline-my.sharepoint.com/:u:/g/personal/thewe60_liu_se/EfK1PKrQ3X9LgOd_8TSw1g0BINzDadmTxHF_RHKg_31dGw?e=SEKX9X&download=1"
        unzip synthD.zip -d ./data

    - name: Run PyTorch Training Loop
      run: |
        apptainer run build/dronalize.sif python train.py --config ci
